# this file is copied into the tty one service
# tty one logs in, hyprlock hides the session
# other ttys still ask for a password

[Service]
ExecStart=
ExecStart=-/usr/sbin/agetty --noreset --noclear --autologin __USER__ --issue-file=/etc/issue:/etc/issue.d:/run/issue.d:/usr/lib/issue.d - ${TERM}
